### ISSUE TITLE
Problem in Bracket

### ISSUE THREAD

**Issue by WeissP** [DogLooksGood/shiftless.el#1]
Wenn I input `999` , I want to get `(` or `()` . But actually it comes `()))`, because every time I input `(` , will emacs automaticly complete with `()`.

**Comment by DogLooksGood** [comment]
because there are so many packages for parentheses, I couldn't find a perfect way without knowing which package is present.

If you use packages like `smartparens`, `paredit`, your `(` will be bound to a command that handle the insertion of pair of parentheses.
```
(setq shiftless-upper-rules
      '((?9 . paredit-open-round)))
```
This will call `paredit-open-round` for `999`. 

Maybe I can check which package is in used.

Any idea or suggestion is appreciated.

**Comment by WeissP** [comment]
Hi
I use Doom Emacs now and I guess `smartparens` is in used. But I don't know what Function can be called to insert a single pair.
I know it's not your job, but I would be glad if you tell me how to resolve it. : )

**Comment by DogLooksGood** [comment]
@WeissP Hi,
you can just query the function by <kbd>C-h k</kbd> (this is the command `describe-key`), then press <kbd>(</kbd>.

**Comment by WeissP** [comment]
I use Evil-mode and wenn I under Insert-mode called `describe-key`, I got only `(self-insert-command N)`.

**Comment by DogLooksGood** [comment]
could you show the output of `describe-mode`, I need the information of what modes are enabled.

**Comment by WeissP** [comment]
```
Enabled minor modes: +Global-Word-Wrap +Popup +Word-Wrap Adaptive-Wrap-Prefix
Async-Bytecomp-Package Auto-Composition Auto-Compression Auto-Encryption
Better-Jumper Better-Jumper-Local Column-Number Company Company-Prescient
Diff-Auto-Refine Display-Line-Numbers Doom-Modeline Eldoc Electric-Indent Evil
Evil-Escape Evil-Goggles Evil-Local Evil-Snipe Evil-Snipe-Local
Evil-Snipe-Override Evil-Snipe-Override-Local Evil-Surround File-Name-Shadow
Flycheck Flycheck-Popup-Tip Font-Lock Gcmh General-Override Git-Gutter
Global-Auto-Revert Global-Company Global-Eldoc Global-Evil-Surround
Global-Flycheck Global-Font-Lock Global-Git-Commit Global-Magit-File
Global-So-Long Global-Subword Global-Undo-Tree Global-Visual-Line
Goto-Address-Prog Highlight-Numbers Highlight-Quoted Hl-Line Hl-Todo Ivy
Ivy-Rich Line-Number Magit-File Menu-Bar Mouse-Wheel Outline Persp
Prescient-Persist Prettify-Symbols Projectile Rainbow-Delimiters Recentf
Save-Place Savehist Server Shell-Dirtrack Show-Paren Size-Indication Smartparens
Smartparens-Global Solaire Solaire-Global Subword Super-Save Tool-Bar
Transient-Mark Undo-Tree Vi-Tilde-Fringe Visual-Line Which-Key Whitespace
Window-Divider Winner Ws-Butler Ws-Butler-Global Yas

(Information about these minor modes follows the major mode info.)

Elisp mode defined in ‘elisp-mode.el’:
Major mode for editing Lisp code to run in Emacs.
```

**Comment by DogLooksGood** [comment]
Ohh, smartparens use hook to insert the close parens, I know the reason of the behavior now.

Let me find a way to fix.

**Comment by DogLooksGood** [comment]
After some investigation, I think it's pretty hard to work with smartparens.
Because after you trigger uppercase, your keyboard is still sending key events, which will be `self-insert-command` in Emacs and smartparens will handle these commands, it will see there's a opening paren before the cursor, so it will provide a closing paren. 

So you can not insert `(` with `999` with smartparens.

And just update to let shiftless only handle a-z and keys defined in rules. 

Leave the issue open till the day I find a solution for this.

**Comment by DogLooksGood** [comment]
With the latest update, add this to your configuration.

```emacs-lisp
(advice-add 'sp--post-self-insert-hook-handler :around #'shiftless--prevent-advice)
```
This will make it work the smartparens, I hope.

**Comment by WeissP** [comment]
Thanks! It works! : )
